# Windows Image Tag
ARG WINDOWS_DOCKER_TAG=1809

FROM mcr.microsoft.com/windows/servercore:$WINDOWS_DOCKER_TAG
COPY asset/ C:/asset/

#############################
## Mid Server Software URL ##
#############################
## Madrid ##
#ENV sn_file_url="https://install.service-now.com/glide/distribution/builds/package/mid/2019/08/12/mid.madrid-12-18-2018__patch4b-07-17-2019_08-12-2019_1850.windows.x86-64.zip"
## New York ##
ENV sn_file_url="https://install.service-now.com/glide/distribution/builds/package/mid/2019/08/27/mid.newyork-06-26-2019__patch1-08-14-2019_08-27-2019_1720.windows.x86-64.zip"

RUN ["powershell.exe","Invoke-WebRequest -uri $env:sn_file_url -OutFile C:\\agent.zip -UseBasicParsing"]
RUN ["powershell.exe","Expand-Archive C:\\agent.zip C:\\_agent_temp\\"]
RUN ["powershell.exe","DEL C:\\agent.zip"]
RUN ["powershell.exe","MOVE C:\\_agent_temp\\agent\\config.xml C:\\asset"]

ENV sn_url=${parameter1:-}
ENV sn_username=${parameter2:-}
ENV sn_password=${parameter3:-}
ENV sn_mid_server_name=${parameter4:-}

CMD ["powershell.exe","C:/asset/init.ps1"]